version: '3.1'

services:

  database:
    image: mysql:5.7
    container_name: smart-home-database
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_MYSQL_DATABASE}
      MYSQL_USER: ${DATABASE_MYSQL_USER}
      MYSQL_PASSWORD: ${DATABASE_MYSQL_PASSWORD}

  esphome:
    image: esphome/esphome:1.13.6
    container_name: smart-home-esphome
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./esphome:/config
