version: '3.1'

services:

  database:
    image: mysql:5.7
    container_name: smart-home-database
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_MYSQL_DATABASE}
      MYSQL_USER: ${DATABASE_MYSQL_USER}
      MYSQL_PASSWORD: ${DATABASE_MYSQL_PASSWORD}

  esphome:
    image: esphome/esphome:latest
    container_name: smart-home-esphome
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./esphome:/config
      - /etc/localtime:/etc/localtime:ro

  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: smart-home-homeassistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - database

  magicmirror:
    image: bastilimbach/docker-magicmirror:latest
    container_name: smart-home-magicmirror
    restart: unless-stopped
    ports:
      - 1024:8080
    volumes:
      - ./magic-mirror/config:/opt/magic_mirror/config
      - ./magic-mirror/modules:/opt/magic_mirror/modules
      - ./magic-mirror/css/custom.css:/opt/magic_mirror/css/custom.css
      - /etc/localtime:/etc/localtime:ro

  pihole:
    image: pihole/pihole:latest
    container_name: smart-home-pihole
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/pihole/etc/pihole:/etc/pihole
      - ./data/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      WEB_PORT: ${PIHOLE_WEB_PORT}
      ServerIP: ${PIHOLE_SERVER_IP}
      DNSMASQ_LISTENING: ${PIHOLE_DNSMASQ_LISTENING}
    dns:
      - 127.0.0.1
      - 1.1.1.1

  transmission:
    image: haugene/transmission-openvpn:2.7
    container_name: smart-home-transmission
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    volumes:
      - /volume1/Transmission/:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      OPENVPN_PROVIDER: ${TRANSMISSION_OPENVPN_PROVIDER}
      OPENVPN_CONFIG: ${TRANSMISSION_OPENVPN_CONFIG}
      OPENVPN_USERNAME: ${TRANSMISSION_OPENVPN_USERNAME}
      OPENVPN_PASSWORD: ${TRANSMISSION_OPENVPN_PASSWORD}
      LOCAL_NETWORK: ${TRANSMISSION_LOCAL_NETWORK}
      WEBPROXY_ENABLED: ${TRANSMISSION_WEBPROXY_ENABLED}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    devices:
      - /dev/net/tun
