version: '3.1'

services:

  database:
    image: mysql:5.7
    container_name: smart-home-database
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_MYSQL_DATABASE}
      MYSQL_USER: ${DATABASE_MYSQL_USER}
      MYSQL_PASSWORD: ${DATABASE_MYSQL_PASSWORD}

  esphome:
    image: esphome/esphome:1.13.6
    container_name: smart-home-esphome
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./esphome:/config

  magic-mirror:
    image: bastilimbach/docker-magicmirror:latest
    container_name: smart-home-magic-mirror
    restart: unless-stopped
    ports:
      - 1024:8080
    volumes:
      - ./magic-mirror/config:/opt/magic_mirror/config
      - ./magic-mirror/modules:/opt/magic_mirror/modules
      - ./magic-mirror/css/custom.css:/opt/magic_mirror/css/custom.css
